### ISSUE TITLE
Not python3 compliant

### ISSUE THREAD

**Issue by Spartan-II-117** [Jerrkawz/GarageQTPi#1]
You don't need to make it python 3 compliant, but specifying that detail would be helpful. Particularly as you're relating it to home-assistant, which is a python3 project.

**Comment by jerrod-lankford** [comment]
Good point, ill add it to the doc. I think Raspbian Jessie comes with python 2.7, thats the main reason I went this route but something to monitor in future releases of raspbian.

**Comment by Spartan-II-117** [comment]
I already had hassbian installed, and that didn't have python-pip only python3-pip
