### ISSUE TITLE
The door would not open or close.

### ISSUE THREAD

**Issue by onlize** [Jerrkawz/GarageQTPi#10]
I have a problem when relay that opens the garage door does not change. I run multiple tests and, as far as I can see, my pin 23 does not change the status when I try to open/close the door. It always has 3.5V. It starts as soon as I start the program.

I see this when I try to open/close door from Home Assistant. I also move sensor to change the status:
![capture](https://user-images.githubusercontent.com/28982031/27815611-258bb6ea-604b-11e7-8ca2-4af84d58b2bd.JPG)

This is my config.yaml file:
![capture](https://user-images.githubusercontent.com/28982031/27844301-25f4f5a2-60e5-11e7-9be4-1e644bf48552.JPG)

This is the entry for this program in configuration.yaml file in Home Assistant:
![capture](https://user-images.githubusercontent.com/28982031/27844271-b17bd9e8-60e4-11e7-9b03-041039d41962.JPG)

Can you please help?

Thank you.

**Comment by onlize** [comment]
I changed configuration file on Home Assistant to:
cover:
  - platform: mqtt
    state_topic: "home-assistant/cover"
    command_topic: "home-assistant/cover/set"
    name: "Garage Door"
    qos: 0
    retain: true

Now it detects the status of the door, but relay would not change. As soon as I run:
sudo python main.py
It closes "Normally Opened" part of relay and keeps it like this until I reboot my RPi.

Any ideas?
Thank you.

**Comment by jerrod-lankford** [comment]
Are you sure the comments are getting published to the topic? Also can you post the logs from GarageQTPi and Home assistant?

**Comment by onlize** [comment]
I believe everything is published the way it should. When I started, I had some additional issues, but I resolved them, so I removed some text.

Where can I get those logs?

Thank you.

**Comment by jerrod-lankford** [comment]
Well you can just post a screen cap of the terminal for garage qt pi. The home assistant log will depend on how its installed. Min is in /var/opt/home-assistant/home-assistant.log

**Comment by onlize** [comment]
I cannot find home-assistant.log file, but this is the terminal screenshot from garage qt pi:
![capture](https://user-images.githubusercontent.com/28982031/27894489-023b0e6a-61d2-11e7-992e-58398bdd82b9.JPG)

Thank you.

**Comment by jerrod-lankford** [comment]
I see a warning at the top about the gpio pin being in use. Can you try restarting the pi and rerunning the program?

**Comment by onlize** [comment]
I restarted and run it multiple times. I always have this warning and the same behavior..

As soon as I run the program, this pin start giving voltage. It does not happen until I start the program. The only way for me to stop it, is to reboot the RPi. Even if I try Ctrl+C to stop the program, it would not release the pin. I have to restart.

Thank you.

**Comment by onlize** [comment]
It seems that the pin actually disconnect the voltage for short period of time if relay is not connected. If relay is connected, the voltage does not change. Does it mean that I have a bad relay? What do you think?

This is a single channel relay and I just purchased it.

Thank you.

**Comment by onlize** [comment]
I confirmed that it was the relay. Thank you for your help.
