### ISSUE TITLE
Question about Raspberry Pi Zero

### ISSUE THREAD

**Issue by onlize** [Jerrkawz/GarageQTPi#11]
Do you think I can use Raspberry Pi Zero? After everything worked for me on Raspberry Pi 3, I decided to try it on RPi Zero and, as far as I can see, everything works.

Can I use it or would you recommend to use RPi 3?

Thank you.

**Comment by jerrod-lankford** [comment]
Yeah I see no reason why it wouldn't work on an rPi zero. I should update my guide for that as its much cheaper. I really only used an rPi3 because i already had one.

**Comment by onlize** [comment]
Great, thank you.
