### ISSUE TITLE
no option for NC switches

### ISSUE THREAD

**Issue by Spartan-II-117** [Jerrkawz/GarageQTPi#2]
Can a configuration option be created to use NC magnetic switches? (reverse open and closed?)

**Comment by jerrod-lankford** [comment]
Was considering this initially. I can add an optional config parameter to the door. Thoughts on a name for the parameter? 

Was thinking something like:

sensor_mode: normally_closed

or

invert_sensor: true

Thoughts?

**Comment by Spartan-II-117** [comment]
I think sensor_mode with NO or NC as options makes the most sense, with the option existing in the config file either way.

**Comment by Spartan-II-117** [comment]
Any chance of getting this implemented?

**Comment by jerrod-lankford** [comment]
Yeah sorry I got busy and forgot about it until the other issue today. I'll knock it out tomorrow

**Comment by Spartan-II-117** [comment]
Awesome, thanks! If I actually knew what I was doing with this stuff I'd have just submitted a PR, but I don't.
