### ISSUE TITLE
Wrong pin for right door in documentation

### ISSUE THREAD

**Issue by reibuehl** [Jerrkawz/GarageQTPi#20]
The graphic from README.md that shows the wiring uses a wrong pin number for the right (blue) sensor wiring. The graphic (and the config.yaml) refer to the pin as GPIO21, but according to https://www.raspberrypi.org/documentation/usage/gpio/ the pin used in the graphic is GPIO27.

**Comment by jerrod-lankford** [comment]
Good catch, seems I have an old pinout diagram. Ill try to update the image when I have time but for now ill make a note in the readme
